learning_log/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topic', views.topics, name='topics'),
    path('topic/<int:topic_id>', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('save_info/', views.save_info, name='save_info'),
    path('show_info/', views.show_info, name='show_info'),
]

app_name = 'learning_logs'

users/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views


urlpatterns = [
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register')
]
app_name = 'users'

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
	
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=True)
	def __str__(self):
		return self.text

class Entry(models.Model):
	
	topic = models.ForeignKey(Topic, on_delete=True)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'entries'
	
	def __str__(self):
		if len(self.text)>50:
			return self.text[:50] + '...'
		else:
			return self.text
		 
class Info(models.Model):
	name = models.CharField(max_length=200)
	sex = models.CharField(max_length=200)
	age = models.IntegerField()

	def __str__(self):
		return self.name

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import  forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets ={'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
import json

from django.core import serializers
from django.shortcuts import render
from .models import Topic, Entry, Info
from .forms import TopicForm, EntryForm
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def index(request):
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return  render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return  render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    '''添加新主题'''
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method !='POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method !='POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@csrf_exempt
def save_info(request):
    if request.method =='POST':
        info = Info()
        data = json.loads(request.body)
        print(info)
        info.name = data['name']
        info.age = data['age']
        info.sex = data['sex']
        info.save()
    return HttpResponse(1)

@csrf_exempt
def show_info(requeset):
    if requeset.method =='POST':
        data = Info.objects.all()
        jso_data = serializers.serialize('json', data, fields=('name', 'sex'))
    return HttpResponse(jso_data)

users/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    if request.method !='POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user =  authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
        {% if user.is_authenticated %}
            Hello, {{ user.username }}.
            <a href="{% url 'users:logout' %}">log out</a>
        {% else %}
            <a href="{% url 'users:register' %}">register</a>
            <a href="{% url 'users:login' %}">log in</a>
        {% endif %}
    </p>
    {% block content %}{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_entry</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block content %}
    <p>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p>
            Learning Log helps you keep track of your learning, for any topic you are learning about.
        </p>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_entry</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </p>
        <p>Add a new entry:</p>
        <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">add entry</button>
        </form>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new_topic</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block content %}
        <p>Add a new topic:</p>

        <form action="{% url 'learning_logs:new_topic' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">add topic</button>
        </form>
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topicDetail</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p>{{ topic }}</p>
        <p>Entries:</p>
        <p>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">add a new entry</a>
        </p>
        <ul>
            {% for entry in entries %}
                <li>
                    <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                    <p>{{ entry.text|linebreaks }}</p>
                    <p>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                    </p>
                </li>
            {% empty %}
                <li>
                    <p>There are no entries for this topic yet.</p>
                </li>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>topics</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p>Topics</p>
        <ul>
            {% for topic in topics %}
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            {% empty %}
                <li>No topics have been added yet.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
    {% endblock content %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}
    {% block content %}
        {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
        {% endif %}
        <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">log in</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    {% endblock %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submint">register</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    {% endblock %}
</body>
</html>